main: maven-main
name: maven-name
author: maven-authors
version: maven-version
description: Have you compass point to a player or a location.
api-version: 1.15
commands:
  ctr:
    description: does things related to the compass tracker
    usage: "Usage: /ctr [ give | who | track | target | targetall | removetarget | cleartargets | targetlist | autogive | autotarget | environment | environmentlist | tickrate ] [args...]"
permissions:
  ctrack.give.self:
    description: Can give a compass to themself
    default: true
  ctrack.give:
    description: Can give a compass to anyone
    default: op
  ctrack.target:
    description: Can manage targets
    default: op
  ctrack.autogive:
    description: Can manage auto giving and auto taking compasses
    default: op
  ctrack.environment:
    description: Can manage permitted environments
    default: op
  ctrack.tickrate:
    description: Can manage compass update rate
    default: op