main: io.github.regenerativep.compasstracker.App
name: CompassTracker
author: regenerativep
version: 1.3.0
description: Have you compass point to a player or a location.
api-version: 1.16
commands:
  ctrack:
    description: does things related to the compass tracker
    usage: "Usage: /ctr [listen | remove | target | stop] [args]"
permissions:
  ctrack.addlistener:
    description: Can add someone as a listener to a target
    default: op
  ctrack.addlistener.self:
    description: Can add theirself as a listener to a target
    default: true
  ctrack.removelistener:
    description: Can remove someone from a target's listeners
    default: op
  ctrack.removelistener.self:
    description: Can remove theirself from a target's listeners
    default: true
  ctrack.addtarget:
    description: Can set someone as a target
    default: op
  ctrack.addtarget.self:
    description: Can set theirself as a target
    default: op
  ctrack.addtargetlocation:
    description: Can set a location as a target
    default: true
  ctrack.removetarget:
    description: Can stop someone from being a target
    default: op
  
